### ISSUE TITLE
Coalition Colleges Cause Problems in Essay Tab

### ISSUE THREAD

**Issue by keskinmbaha** [ashwinxkumar01/apps-college#47]
When there is colleges that only accept coalition or basically any time when coalition is the site in which all colleges have an application for, on the essays tab there is no information icon anymore and when there is a mix of coalition and common app, the common app essays do not show up.

**Comment by gmihir** [comment]
I pushed a fix, can you confirm it’s resolved

**Comment by keskinmbaha** [comment]
The information icon still does not show up when there are 3 colleges, two with only coalition and one with only common. That is all I tested so far.

**Comment by gmihir** [comment]
It's not supposed to. It's only supposed to show up when only coalition or common app is required. basically only when all colleges accept one or the other, while at least one of them accepts the other as well

**Comment by keskinmbaha** [comment]
Ah okay. My bad. Then it works right now. Closing the issue.
